// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: liveness.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LivenessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessRequest) Reset() {
	*x = LivenessRequest{}
	mi := &file_liveness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessRequest) ProtoMessage() {}

func (x *LivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessRequest.ProtoReflect.Descriptor instead.
func (*LivenessRequest) Descriptor() ([]byte, []int) {
	return file_liveness_proto_rawDescGZIP(), []int{0}
}

type LivenessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessResponse) Reset() {
	*x = LivenessResponse{}
	mi := &file_liveness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessResponse) ProtoMessage() {}

func (x *LivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessResponse.ProtoReflect.Descriptor instead.
func (*LivenessResponse) Descriptor() ([]byte, []int) {
	return file_liveness_proto_rawDescGZIP(), []int{1}
}

func (x *LivenessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessRequest) Reset() {
	*x = ReadinessRequest{}
	mi := &file_liveness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessRequest) ProtoMessage() {}

func (x *ReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessRequest.ProtoReflect.Descriptor instead.
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return file_liveness_proto_rawDescGZIP(), []int{2}
}

type ReadinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessResponse) Reset() {
	*x = ReadinessResponse{}
	mi := &file_liveness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResponse) ProtoMessage() {}

func (x *ReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResponse.ProtoReflect.Descriptor instead.
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return file_liveness_proto_rawDescGZIP(), []int{3}
}

func (x *ReadinessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_liveness_proto protoreflect.FileDescriptor

const file_liveness_proto_rawDesc = "" +
	"\n" +
	"\x0eliveness.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fLivenessRequest\",\n" +
	"\x10LivenessResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10ReadinessRequest\"-\n" +
	"\x11ReadinessResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb3\x01\n" +
	"\x0fLivenessService\x12M\n" +
	"\x04Live\x12\x16.proto.LivenessRequest\x1a\x17.proto.LivenessResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/health/live\x12Q\n" +
	"\x05Ready\x12\x17.proto.ReadinessRequest\x1a\x18.proto.ReadinessResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/health/readyB.Z,github.com/sepulchrestudios/go-service/protob\x06proto3"

var (
	file_liveness_proto_rawDescOnce sync.Once
	file_liveness_proto_rawDescData []byte
)

func file_liveness_proto_rawDescGZIP() []byte {
	file_liveness_proto_rawDescOnce.Do(func() {
		file_liveness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liveness_proto_rawDesc), len(file_liveness_proto_rawDesc)))
	})
	return file_liveness_proto_rawDescData
}

var file_liveness_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_liveness_proto_goTypes = []any{
	(*LivenessRequest)(nil),   // 0: proto.LivenessRequest
	(*LivenessResponse)(nil),  // 1: proto.LivenessResponse
	(*ReadinessRequest)(nil),  // 2: proto.ReadinessRequest
	(*ReadinessResponse)(nil), // 3: proto.ReadinessResponse
}
var file_liveness_proto_depIdxs = []int32{
	0, // 0: proto.LivenessService.Live:input_type -> proto.LivenessRequest
	2, // 1: proto.LivenessService.Ready:input_type -> proto.ReadinessRequest
	1, // 2: proto.LivenessService.Live:output_type -> proto.LivenessResponse
	3, // 3: proto.LivenessService.Ready:output_type -> proto.ReadinessResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_liveness_proto_init() }
func file_liveness_proto_init() {
	if File_liveness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liveness_proto_rawDesc), len(file_liveness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_liveness_proto_goTypes,
		DependencyIndexes: file_liveness_proto_depIdxs,
		MessageInfos:      file_liveness_proto_msgTypes,
	}.Build()
	File_liveness_proto = out.File
	file_liveness_proto_goTypes = nil
	file_liveness_proto_depIdxs = nil
}
